### ISSUE TITLE
Nomes das funções

### ISSUE THREAD

**Issue by laisbastosbg** [lvasantos/taxCalc#1]
Algumas funções poderiam ter nomes mais descritivos, por exemplo:

https://github.com/lvasantos/taxCalc/blob/d2288eeffcc7d90e97e450d52892a921468dfb76/Sources/conversor/Conversor.swift#L5

poderia ser 
```swift
func getDolarValueInReal()
```

**Comment by lvasantos** [comment]
Oi, Lais !

As funções foram rescritas  de forma mais descritivas. Obrigada pelo toque !
