### ISSUE TITLE
Sugestão: Criar versão executável

### ISSUE THREAD

**Issue by otavioalbucosta** [lvasantos/taxCalc#2]
Boa tarde Luciana, tudo bem? 
Gostei muito do seu código, mas dificulta um pouco não poder executar ele de forma independente. Para resolver isso, sugiro criar um executável para o seu package, e ele seria feito dessa forma:

1. Criar produto executável e target executável no Package.swift:
  https://github.com/lvasantos/taxCalc/blob/d2288eeffcc7d90e97e450d52892a921468dfb76/Package.swift#L8-L10
No local acima, adicionar em products uma versão executável do produto. Exemplo:
```swift
products: [
        .library(name: "conversor", targets:["conversor"]),
        .executable(name: "conversorExec", targets: ["conversorExec"])
    ],
```
Em targets, a seguinte alteração deve ser feita:

```swift
targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "conversor",
            dependencies: ["SwiftSoup"]),
        .executableTarget(
            name: "conversorExec",
            dependencies: ["conversor"]
        ),
        .testTarget(
            name: "conversorTests",
            dependencies: ["conversor"]),
    ]
```
Na sua pasta Sources, uma nova pasta de nome conversorExec deve ser criada com o seu arquivo main.swift, precisando chamar apenas a função main do App.swift

**Comment by lvasantos** [comment]
Obrigada, Otavio !

A sugestão foi aplicada e já está funcional !
