### ISSUE TITLE
Sugestões.

### ISSUE THREAD

**Issue by Luizerz** [lvasantos/taxCalc#4]
### Primeiramente, parabéns pela coragem do programa, extremamente limpa e legível, consegui entender muito bem seu código e a funcionalidade dele é perfeita. Um conselho que poss te dar é de tirar os casos que voce não esta usando.
https://github.com/lvasantos/taxCalc/blob/8e1ff115a9f637f61b7a2418da4e2b4971fcde6d/Sources/conversor/Conversor.swift#L90-L101  
### E por fim para algo mais futuro, ler um pouco pra vê se tem como chamar diariamente/semanalmente a taxa variável, pois no código a taxa variável realmente não e variável.
https://github.com/lvasantos/taxCalc/blob/8e1ff115a9f637f61b7a2418da4e2b4971fcde6d/Sources/conversor/Conversor.swift#L33-L37  
### De resto, parabéns pelo trabalho, ameiiii muito <3

**Comment by lvasantos** [comment]
Oi, Luiz !

Obrigada pelas sugestões !
Mostrar o valor bruto é definitivamente algo que eu acho legal para implementar.
Coloquei uns nomes mais descritivos nas funções e nas variáveis.
