### ISSUE TITLE
Sugestão 

### ISSUE THREAD

**Issue by paulohgs** [lvasantos/taxCalc#5]
E aí Ivasantos, tudo certo?

Gostei bastante da sua aplicação, realmente é algo bem útil e curti muito essa ideia, pois trata-se de algo corriqueiro do dia-a-dia de muitas pessoas.

Deixo aqui uma sugestão para futuras melhorias em seu projeto, que seria a sugestão do uso de Property Wrappers, por possuir bastante structs e diversas variáveis constantes, criar uma property wrapper pode te fazer economizar mais tempo e deixar o código bem mais legível também, então fica a dica pra próxima e parabéns pelo projeto e pela sua evolução 🐿️!

**Comment by paulohgs** [comment]
Algo que acabei esquecendo, aqui um link para ajudar a entender melhor sobre:
[Property Wrapper](https://www.swiftbysundell.com/articles/property-wrappers-in-swift/)
Deixo aqui também o link direto para a documentação do swift sobre properties para ajudar a se ter uma base quanto a property wrapper:
[Properties](https://docs.swift.org/swift-book/LanguageGuide/Properties.html)

**Comment by lvasantos** [comment]
Oi oi Paulo !

Que sugestão legal, era algo que eu não sabia. Vou dar uma olhada e certeza implementar no futuro. 
Obrigada ! ✨
