### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by trastoan** [lvasantos/taxCalc#7]
1. Dividir suas classes e structs em arquivos diferentes.
2. Uso de closures ou de async/await nas requisições de rede, removendo a necessidade de controlar a função com o RunLoop.
3. Tentar misturar menos nomes de funções e variáveis no inglês e português, dar preferencia para código em inglês.

**Comment by lvasantos** [comment]
Oi, oi !

Obrigada pela sugestão. Adoraria um feedback.
